permalink: /:year/:month/:day/:title

highlighter: pygments
markdown: kramdown

title : Orbitist News
shortcut_icon: http://orbitist.s3.amazonaws.com/_toplevel/images/logos/icon-120.png
apple_touch_icon: http://orbitist.s3.amazonaws.com/_toplevel/images/logos/400_illustrated.jpg

baseurl : http://news.orbitist.com
  
timezone : America/New_York
