permalink: /:year/:month/:day/:title 

pygments: true

markdown: kramdown

title : Orbitist
tagline: Stories on maps
author : 
  name : Orbitist Support
  email : support@orbitist.com
  github : Orbitist
  twitter : TheOrbitist
  web : http://www.orbitist.com

production_url : orbitist.com

baseurl : http://orbitist.com  
        
analytics :
  google : 
    tracking_id : 'UA-50308061-1'


authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: Founder of Orbitist. New Media Manager at SUNY Fredonia. Multimedia Storyteller.
    image: http://orbitist.s3.amazonaws.com/_toplevel/images/profile-images/ngunner.jpg
    email: gunnernr@gmail.com
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
  jpaton:
    name: Jason Paton
    display_name: Jason Paton
    bio: 
    image: https://pbs.twimg.com/profile_images/455728324975656960/vpELoM_p.jpeg
    email: pato9955@fredonia.edu
    web: 
    twitter: knotfloyd
    github: pato9955
  azaremski:
    name: Adam Zaremski
    display_name: Adam Zaremski
    bio: Reporter with East Aurora Advertiser @eastauroranews. Other days- creator and drinker of fine brews. Always enjoying life.
    image: https://pbs.twimg.com/profile_images/3146366407/aa2927c576bac48ac1410a546861252b.jpeg
    email: adam.zaremski@gmail.com
    web: 
    twitter: azaremski
    github:
  rbretl:
    name: Rebekah Bretl
    display_name: Rebekah Bretl
    bio: E-counceller at the State University of New York at Fredonia, freelance maker at Orbitist.
    image: https://pbs.twimg.com/profile_images/378800000422132193/64778d05073607b1a17d152d56936d45.jpeg
    email: bretl@fredonia.edu
    web: 
    twitter: BekahBr
    github:
  jmorlock:
    name: Jeremy Morlock
    display_name: Jeremy Morlock
    bio: Media professional. Proud East Auroran.
    image: https://pbs.twimg.com/profile_images/456838244856909824/LwGnhTR5.jpeg
    email: jmorlock2@gmail.com
    web: 
    twitter: typewriter84
    github:
  mdrzewiecki:
    name: Margaret Drzewiecki
    display_name: Margaret Drzewiecki
    bio:
    image: https://pbs.twimg.com/profile_images/468743978062729216/1bcLAO5j.jpeg
    email: drze6512@fredonia.edu
    web: 
    twitter: drzmj
    github:

  
timezone : America/New_York


prose:
  siteurl: 'http://www.orbitist.com'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - CNAME
    - /css
    - index.html
    - /plugins
    - README.MD
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published?"
          value: "true"
      - name: "listed"
        field:
          element: "checkbox"
          label: "Listed?"
          value: "true"
      - name: "sponsored"
        field:
          element: "checkbox"
          label: "Sponsored?"
          value: "true"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments?"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "description"
        field:
          element: "text"
          label: "Description"
      - name: "author"
        field:
          element: "text"
          label: "Author username"
      - name: "sources"
        field:
          element: "text"
          label: "Enter sources here."
      - name: "image"
        field:
          element: "text"
          label: "Featured image"
      - name: "latitude"
        field:
          element: "text"
          label: "Latitude"
      - name: "longitude"
        field:
          element: "text"
          label: "Longitude"
      - name: "zoom"
        field:
          element: "text"
          label: "Initial zoom level"
      - name: "title"
        field:
          element: "text"
          label: "Slide title"
      - name: "maxZoom"
        field:
          element: "text"
          label: "Maximum zoom level"
      - name: "basemap"
        field:
          element: "select"
          label: "Base Map"
          placeholder: "Choose basemap"
          options:
            - name: "Orbitist streets"
              value: "orbitist.ie90k9cc"
            - name: "Orbitist satellite"
              value: "orbitist.if1em1bg"
            - name: "Orbitist terrain"
              value: "orbitist.if61m31c"
            - name: "Orbitist light"
              value: "orbitist.ina586ah"
      - name: "tilemilltiles"
        field:
          element: "text"
          label: "Tilemill tiles code"
      - name: "cartodbapi"
        field:
          element: "text"
          label: "CartoDB API Code"
      - name: "orbitistapi"
        field:
          element: "text"
          label: "Orbitist API code"
      - name: "customjs"
        field:
          element: "text"
          label: "Link to custom JS file"
