permalink: /:year/:month/:day/:title 

pygments: true

markdown: kramdown

title : The Orbitist
tagline: Mapping the Universe
author : 
  name : Orbitist Support
  email : support@orbitist.com
  github : Orbitist
  twitter : TheOrbitist
  web : http://www.orbitist.com

production_url : orbitist.com

baseurl : http://orbitist.github.io

 
comments :
  provider : disqus
  disqus :
    short_name : 
   
        
analytics :
  google : 
    tracking_id : 'UA-50308061-1'


authors:
  ngunner:
    name: Nicholas Gunner
    display_name: Nicholas Gunner
    bio: Founder of Orbitist. New Media Manager at SUNY Fredonia. Multimedia Storyteller.
    image: http://orbitist.s3.amazonaws.com/_toplevel/images/profile-images/ngunner.jpg
    email: gunnernr@gmail.com
    web: http://www.nicholasgunner.com
    twitter: nicholas_gunner
    github: ngunner
   
  
timezone : America/New_York